//    uniCenta oPOS  - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2018 uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.
package com.openbravo.pos.catalog;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author adrianromero
 */
public class JCatalogTab extends javax.swing.JPanel {

//    private JFlowPanel flowpanel;
    /**
     * Creates new form JCategoryProducts
     */
    public JCatalogTab() {
        initComponents();

//        flowpanel = new JFlowPanel();
//        flowpanel.setOpaque(false);
//        flowpanel.setBackground(new Color(20, 20, 20));
//        JScrollPane scroll = new JScrollPane(flowpanel);
//        scroll.setOpaque(false);
//        add(scroll, BorderLayout.CENTER);
    }

    @Override
    public void setEnabled(boolean value) {
        flowpanel.setEnabled(value);
        super.setEnabled(value);
    }

    /**
     *
     * @param ico
     * @param al
     * @param textTip
     */
    public void addButton(Icon ico, ActionListener al, String textTip) {
        JButton btn = new JButton();
        btn.applyComponentOrientation(getComponentOrientation());
        btn.setIcon(ico);
        btn.setFocusPainted(false);
        btn.setFocusable(false);

        if (textTip != null) {
            btn.setToolTipText(textTip);
        }

        btn.setRequestFocusEnabled(false);
        btn.setHorizontalTextPosition(SwingConstants.CENTER);
        btn.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn.setMargin(new Insets(2, 2, 2, 2));
        btn.addActionListener(al);

        flowpanel.add(btn);
    }
    
    public void setScrollValue(int value) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                scroll.getVerticalScrollBar().setValue(value);
            }
        });
    }
    
    public int getScrollValue()
    {
        return scroll.getVerticalScrollBar().getValue();
    }
    
    public int getScrollHeight() {
        return scroll.getSize().height;
    }

    public int getScrollContent(){
        return flowpanel.getSize().height;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        flowpanel = new com.openbravo.beans.JFlowPanel();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        scroll.setBorder(null);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0));

        flowpanel.setOpaque(false);
        scroll.setViewportView(flowpanel);

        add(scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.openbravo.beans.JFlowPanel flowpanel;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

}
